perf-test/package-lock.json, perf-test/package.json
This [release](https://github.com/LottieFiles/dotlottie-web/releases/tag/%40lottiefiles%2Fdotlottie-react%400.6.0) optimize animation playback based on initial visibility. 
Related #5
=> chore: 🤖 update dotlottie-react 0.6.0

package.json, src/lottie-player.ts
- Correct the license date and current version of NPM
- Update repository URLs
=> Fix and correct package info

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.13.6 released wasm binary
=> lottie: Release v1.0.0-beta.19

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.13.7 released wasm binary
=> lottie: Release v1.0.0-beta.20

perf-test/app/page.tsx
=> perf-test: Fix the invalid font color from light mode

perf-test/app/page.tsx, perf-test/components/SkottiePlayer/index.tsx, perf-test/next.config.mjs, perf-test/package-lock.json, perf-test/package.json
Integration of Skottie Player from [canvaskit-wasm](https://www.npmjs.com/package/canvaskit-wasm).
[Performance Result]
- Renderer : Skia SW Canvas
- Animation count : 20
- Seed : [link](https://thorvg-perf-test-git-jinny-skottie-thorvg-web.vercel.app/?seed=aXNvbWV0cmljLGZsaXBwaW5nX3BhZ2Usdm9pY2VfcmVjb2duaXRpb24sbWVyZ2luZ19zaGFwZXMsZG93bixjYXRfbG9hZGVyLHRleHQyLGFsaWVuLGxvbG8saW5zdGFfY2FtZXJhLGhvdXJnbGFzcyxlbW9qaV9lbmpveWluZyxjYXRfbG9hZGVyLHNhZF9lbW9qaSxiaXJ0aF9zdG9uZV9sb2dvLHNhZF9lbW9qaSwxMTU1NSxzdGFydHNfdHJhbnNwYXJlbnQsbWF0ZXJpYWxfd2F2ZV9sb2FkaW5nLGFic3RyYWN0X2NpcmNsZQ%3D%3D&player=skia%2Fskottie&count=20) 
- FPS : 25~38FPS
- LightHouse Score : 68
=> perf-test: Added skottie player

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.13.8 released wasm binary
=> lottie: Release v1.0.0-beta.21

perf-test/app/page.tsx
It's time to enable DPR since thorvg/skottie have it.
=> perf-test: remove dotLottie DPR turning off.

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.1 released wasm binary
=> lottie: Release v1.0.0-beta.23

package.json, perf-test/package-lock.json, perf-test/package.json, src/lottie-player.ts
New release for DPR support
- Introduce DPR and renderConfig option
Revert temporal DPR config.
=> lottie: Release v1.0.0-beta.24

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.2 released wasm binary
=> lottie: Release v1.0.0-beta.25

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.3 released wasm binary
=> lottie: Release v1.0.0-beta.26

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.4 released wasm binary
=> lottie: Release v1.0.0-beta.27

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.5 released wasm binary
=> lottie: Release v1.0.0-beta.28

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.6 released wasm binary
- Fix `getVersion` function
=> lottie: Release v1.0.0-beta.29

package.json, perf-test/app/page.tsx, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.7 released wasm binary
- perf-test: Bump up version (thorvg, dotlottie)
- perf-test: Enable lottie-web comparison
=>  lottie: Release v1.0.0-beta.30

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.8 released wasm binary
=> lottie: Release v1.0.0-beta.31

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.9 released wasm binary
=>  lottie: Release v1.0.0-beta.32

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.14.10 released wasm binary
=> lottie: Release v1.0.0-beta.33

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v0.15.0 released wasm binary
=> lottie: Release v1.0.0-beta.36

package.json
see: https://github.com/thorvg/thorvg/pull/2838
=> fix packaging error on ubunutu

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v1.0.0-pre1 released wasm binary
=> lottie: Release v1.0.0-pre.1

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v1.0.0-pre2 released wasm binary
=> lottie: Release v1.0.0-pre.2

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v1.0.0-pre3 released wasm binary
=> lottie: Release v1.0.0-pre.3

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v1.0.0-pre4 released wasm binary
=> lottie: Release v1.0.0-pre.4

src/lottie-player.ts
issue: #2721
Found thorvg.web missed removing TVG stuffs, which is already removed from the viewer.
=> Spec out TVG Binary

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v1.0.0-pre6 released wasm binary
=>  lottie: Release v1.0.0-pre.6

example/webgl.html, src/lottie-player.ts
see history: https://github.com/thorvg/thorvg/issues/2837
=> lottie: Support WebGL

package.json, perf-test/app/page.tsx, perf-test/package-lock.json, perf-test/package.json
- Update v1.0.0-pre7 released wasm binary
- Support WebGPU player in perf-test
=> lottie: Release v1.0.0-pre.7 

package.json, perf-test/package-lock.json, perf-test/package.json
- Update v1.0.0-pre8 released wasm binary
=> lottie: Release v1.0.0-pre.8

src/lottie-player.ts
This change enables users to host and use their own WASM file instead of relying on unpkg.com CDN.
- Add wasmUrl property to allow custom WASM file location
- Move WASM module initialization inside component
- Keep default unpkg.com URL as fallback
Users can specify a custom WASM URL in the following scenarios:
- When they want to use their own built binary (specific engine/build, compact binary)
- When they prefer to use their own CDN hosting due to network performance considerations
```html
<lottie-player
src="path/to/animation.json"
wasmUrl="https://my-cdn.com/thorvg-wasm.wasm"
autoplay
></lottie-player>
```
=> lottie: Support custom WASM URL

src/lottie-player.ts
This commit is aligned with https://github.com/thorvg/thorvg/pull/3034, as changes to the WASM binary interface require updates to the JS binding layer.
---
Confirmed that after the patch, the rendering process functions the same as before, with a reduced WASM binary size.
https://github.com/user-attachments/assets/ece27c12-a473-458c-993a-b58dfc7eb8b8
=> lottie: apply wasm binary size reduction

package.json, perf-test/package-lock.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre10 released wasm binary
=> lottie: Release v1.0.0-pre.10

package.json, perf-test/package-lock.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre11 released wasm binary
=> lottie: Release v1.0.0-pre.11

package.json, perf-test/package-lock.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre12 released wasm binary
=> lottie: Release v1.0.0-pre.12

package.json, perf-test/package-lock.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre13 released wasm binary
=> lottie: Release v1.0.0-pre.13

src/lottie-player.ts
issue: https://github.com/thorvg/thorvg/issues/3248
=> lottie: add .lot file type

package.json, perf-test/package-lock.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre15 released wasm binary
=> lottie: Release v1.0.0-pre.15

perf-test/app/page.tsx
Currently, the file type does not need to be displayed, as only the JSON format is supported.
=> perf-test: remove file type information

package.json, perf-test/package-lock.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre16 released wasm binary
=> lottie: Release v1.0.0-pre.16

package.json, perf-test/package-lock.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre17 released wasm binary
=> lottie: Release v1.0.0-pre.17

package.json, perf-test/package-lock.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre18 released wasm binary
=> lottie: Release v1.0.0-pre.18

package.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre20 released wasm binary
=> lottie: Release v1.0.0-pre.20

package.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre21 released wasm binary
=> lottie: Release v1.0.0-pre.21

package.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre25 released wasm binary
=> lottie: Release v1.0.0-pre.25

package.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre26 released wasm binary
=> lottie: Release v1.0.0-pre.26

src/base-lottie-player.ts
culprit: 24326642a3ecbf47a08f201b9241147f6f5d84a1
=> lottie: hotfix TVG.load() not being called

package.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre27 released wasm binary
=> lottie: Release v1.0.0-pre.27

README.md, src/base-lottie-player.ts
Enable dynamic animation quality control.
New API
- setQuality(value: number) : void
Usage:
```js
const player = document.querySelector('lottie-player');
player.setQuality(80); // Set high quality
```
issue: https://github.com/thorvg/thorvg.web/issues/151
=> lottie: support quality control

package.json, perf-test/package.json, perf-test/yarn.lock
- Update v1.0.0-pre29 released wasm binary
Used emsdk ver: 4.0.6
=> lottie: Release v1.0.0-pre.29
